<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Hotcakes.Web">
      <HintPath>..\dll\Hotcakes.Web.dll</HintPath>
    </Reference>
    <Reference Include="Hotcakes.CommerceDTO">
      <HintPath>..\dll\Hotcakes.CommerceDTO.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\dll\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="System.Web.Extensions">
      <HintPath>..\dll\System.Web.Extensions.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Costura.Fody" Version="6.2.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="SkiaSharp" Version="3.119.2" />
    <PackageReference Include="SkiaSharp.Views.WindowsForms" Version="3.119.2" />
  </ItemGroup>

</Project>